### ISSUE TITLE
Sprint 0 - Definição de papéis

### ISSUE THREAD

**Issue by Thais-ra** [fga-eps-mds/2021-1-Bot#10]
Papéis:
- Scrum Master
- PO
- Arquitet@
- Devops
- Tecnologista
- Tecnologista

**Comment by AnaCarolinaRodriguesLeite** [comment]
Houve uma separação sobre as funções de cada um, por meio do nosso canal de comunicação no discord(com informações onde a discussão tem cunho mais direto), no qual ficou: 
Scrum Master : Matheus
PO: Ana Carolina
Arquiteta: Lara
Devops1: Eduardo
Devops2: Thais
Tecnologista: ainda esta na decisão de escolha.
