### ISSUE TITLE
Sprint 0 - Organizar horarios dos membros

### ISSUE THREAD

**Issue by Thais-ra** [fga-eps-mds/2021-1-Bot#11]
Definir melhor horário para o time se reunir semanalmente para as sprints planning, além de deixar claro os melhores horários para cada membro realizar pareamentos.
- [x] Criar uma planilha
- [x] Todos os membros preencherem com seus horários disponíveis/vagos

**Comment by LamequeFernandes** [comment]
A seguir, link com a planilha de horários "livres" de cada um dos membros:
https://docs.google.com/spreadsheets/d/1I8LEH8eR2xAUQq63SwqnBtVvWprClk0BlHGAnlG_q6k/edit#gid=96807035
