### ISSUE TITLE
Sprint 1 - Estudo de tecnologias

### ISSUE THREAD

**Issue by gatotabaco** [fga-eps-mds/2021-1-Bot#12]
O grupo precisa compreender completamente as tecnologias que vai trabalhar durante o semestre. Primeiramente os tecnologistas terão que descobrir os melhores materiais para estudo, estuda-los e fazer uma replicação para o restante do grupo. Entre as tecnologias que compreendemos como fundamentais para o projeto, está o **framework rasa e a linguagem Python.**

- [ ] @LamequeFernandes e @MegahNevel Previamente juntam os materiais e estudam
- [ ] Grupo deve estudar Rasa
- [ ] Grupo deve estudar as bibliotecas que vai trabalhar em Python

**Comment by Thais-ra** [comment]
https://github.com/lappis-unb/rasa-ptbr-boilerplate

**Comment by MegahNevel** [comment]
https://rasa.com/

**Comment by LamequeFernandes** [comment]
Blogs sobre o basico do framework Rasa:
https://medium.com/rapaduratech/criando-um-chatbot-com-o-rasa-efecb0195f48
https://blog.brq.com/rasa-2-0-criando-um-chatbot-com-uma-poderosa-ferramenta-open-source/

**Comment by gatotabaco** [comment]
O grupo entendeu que estudar as tecnologias é uma tarefa que abrange todo o decorrer do semestre, portanto, concluímos que essa Issue será fechada com a conclusão de que trabalharemos com o **Framework Rasa e a linguagem Python.**
