### ISSUE TITLE
Sprint 1 - Primeiro contato com o cliente

### ISSUE THREAD

**Issue by gatotabaco** [fga-eps-mds/2021-1-Bot#13]
O primeiro contato com o cliente 'Paulo Guerra' deve ser feito por algum dos PO's, de algum dos times, de modo que seja organizada uma reunião envolvendo os 3 grupos e o cliente. Essa reunião será importante para organizarmos os trabalhos.

- [x] Conexão e organização entre os 3 grupos para decidir qual PO vai ficar em contato mais próximo com o cliente
- [x] Marcar um dia interessante para que pelo menos os 3 PO's possam estar presentes em uma reunião **remota** com o cliente
- [x] Reunião concluída

**Comment by AnaCarolinaRodriguesLeite** [comment]
Foi feita a conexão com os POs dos grupos e definimos que eu ficaria na comunicação direta com o cliente.
O dia da reunião marcada foi 04/08/2021 tendo sido realizada as 09:00, pautando as dúvidas feitas por cada PO.
