### ISSUE TITLE
[Bug] Links da parte de contribuição não funcionam

### ISSUE THREAD

**Issue by yudi-azvd** [fga-eps-mds/2021-1-Bot#132]
## Descrição da Issue
Os links 1 e 2 em [como contribuir](https://github.com/fga-eps-mds/2021-1-Bot#-como-contribuir-para-o-projeto) não funcionam.

Acho que o ideal para link é usar o caminho relativo para o arquivo em vez da URL no github.

Exemplos:

```md
[Guia de Contribuição](docs/CONTRIBUTING.md)

[Código de Conduta](docs/CODE_OF_CONDUCT.md)
```

Se você estiver no VSCode, você pode verificar o funcionamento dos links no previewer de markdown embutido. Basta pressionar `Ctrl+K` e depois  `V`, separadamente.

**Comment by gatotabaco** [comment]
Pull Request criado. Aguardando apenas revisão
