### ISSUE TITLE
Alterar nomenclatura da politica de branch

### ISSUE THREAD

**Issue by LamequeFernandes** [fga-eps-mds/2021-1-Bot#159]
## Descrição da Issue
Mudança na nomenclatura de branch, pois da forma que está, por conta dos parênteses não é possível realizar o autocomplete no terminal

## Tasks:
- [x] Mudança da nomeclatura de branch no documento de politica da mesma.

## Critérios de Aceitação:
- [x] Não utilizar parênteses.

**Comment by LamequeFernandes** [comment]
Alterações realizadas, anteriormente o formato de branch era da seguinte forma:
*prefixo(#númeroDaIssue)/assunto*
exemplo: *feature(#87)/exemplo-teste*

Após a realização das tarefas apresentadas na issue:
*prefixo#númeroDaIssue/assunto*
exemplo: *feature#87/exemplo-teste*

**Comment by gatotabaco** [comment]
@LamequeFernandes setar Estimate
