### ISSUE TITLE
Integrar as funcionalidades -Regras para lugares específicos

### ISSUE THREAD

**Issue by Ericklevy** [fga-eps-mds/2021-1-Bot#169]
## Descrição da Issue
Regras para lugares específicos para o bot

## Tasks:
- [x] US10  @LamequeFernandes 
- [x] US11  @LamequeFernandes 
- [x] US14  @kayrocesar 
- [x] US15  @kayrocesar
- [x] US16  @kayrocesar
- [x] US17 @kayrocesar 
- [x] US18 @DouglasMonteles 
- [x] US19 @DouglasMonteles 
- [x] US20 @Ericklevy 

## Critérios de Aceitação:
- [ ] Revisão de pelo menos um membro de cada equipe

**Comment by gatotabaco** [comment]
@Ericklevy , colocar Labels na Issue

**Comment by Ericklevy** [comment]
arrumei
