### ISSUE TITLE
Sprint 1 - Criar uma proposta de template para Issues 

### ISSUE THREAD

**Issue by gatotabaco** [fga-eps-mds/2021-1-Bot#19]
O repositório precisa ser padronizado para as futuras contribuições, por isso, os grupos tem que entrar em acordo em um modelo para as issues futuras.

- [x] Formatação em padrão markdown
- [x] Linguagem padrão PT-BR
- [x] Versionamento do documento 
- [ ] ~Apresentar a proposta para os demais grupos~
- [x] Fazer ajustes se necessário

**Comment by Thais-ra** [comment]
Descobri que tem como criar mais de um template, então se a galera de outros times quiserem podem criar o próprio template de issue.

**Comment by gatotabaco** [comment]
O template do time capivara foi criado e, portanto, essa issue está fechada.
