### ISSUE TITLE
Sprint 1 - Criar uma proposta de template para a documentação

### ISSUE THREAD

**Issue by gatotabaco** [fga-eps-mds/2021-1-Bot#20]
É necessário um template para a documentação do projeto

- [x] Formato do nome do documento
- [x] Formato do histórico de revisões
- [x] Formato da parte de referências

**Comment by LamequeFernandes** [comment]
Template para a documentação do projeto criado, segui no link:
https://github.com/fga-eps-mds/2021-1-Bot/blob/templates/docs/templete.md
