### ISSUE TITLE
Reunião geral sobre a release 2

### ISSUE THREAD

**Issue by HenriqueHida** [fga-eps-mds/2021-1-Bot#214]
## Descrição da Issue
Reunião com todos os integrantes do chatBot para decidir como será a release 2

## Tasks:
- [x] Marcar reunião 
- [x] Realizar reunião 

## Critérios de Aceitação:
- [ ] Release 2 esclarecida

**Comment by gatotabaco** [comment]
@HenriqueHida adicionar Assignees

**Comment by gatotabaco** [comment]
@HenriqueHida adicionar estimate

**Comment by HenriqueHida** [comment]
@gatotabaco esta será uma reunião geral, logo todos estão atribuidos

**Comment by kayrocesar** [comment]
A reunião  geral dos  grupos foi realizada via Discord  com o objetivo de esclarecer alguns pontos sobre a release 2. Foram tomadas as seguintes decisões:

- Prioridade na implementação de  funcionalidades que utilizem API
- Aprimorar o Backlog
- Acrescentar mais funcionalidades que envolvam respostas de FAQ (de acordo com a nova versão do Backlog)
-  Se for viável, aprimorar a personalidade do Bot

**Comment by gatotabaco** [comment]
@HenriqueHida Sendo assim, acho que vale marcar todos que participaram na reunião. É importante para fins de rastreio.

Além disso, é importante setar um estimate para a issue
