### ISSUE TITLE
Alteração na politica de branch

### ISSUE THREAD

**Issue by LamequeFernandes** [fga-eps-mds/2021-1-Bot#222]
## Descrição da Issue
A politica de branch está informando que utilizaremos uma branch chamada develop, para intermediar entre a main e as demais, porém, não a utilizaremos.

## Tasks:
- [x] Apagar informações sobre brach develop.

## Critérios de Aceitação:
- [x] Revisão de pelo menos um membro.

**Comment by LamequeFernandes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Time-Capivara-6102b4a201b9d1001095882d/issues/fga-eps-mds/2021-1-Bot/222?planning-poker) with ZenHub @gatotabaco @Thais-ra @klmurussi @AnaCarolinaRodriguesLeite

**Comment by gatotabaco** [comment]
@LamequeFernandes pode fechar a issue? Linka o PR a ela

**Comment by LamequeFernandes** [comment]
Alteração realizada, PR:
https://github.com/fga-eps-mds/2021-1-Bot/pull/227
