### ISSUE TITLE
Sprint 1 - Preparação

### ISSUE THREAD

**Issue by HenriqueHida** [fga-eps-mds/2021-1-Bot#23]
O grupo precisa entrar em acordo no quesito divisão de cargos e as tecnologias que serão utilizadas para realização do trabalho.

Tasks:
- [x] Task 1: Dividir os cargos de todos os membros do grupo.
- [ ] Task 2: Decidir quais tecnologias serão usadas.

Após o cumprimento das tasks, deve-se iniciar os estudos das tecnologias que serão adotadas.

**Comment by RochaCarla** [comment]
qual status dessa issue?
