### ISSUE TITLE
Alteração do backlog

### ISSUE THREAD

**Issue by PedroLSF** [fga-eps-mds/2021-1-Bot#230]
## Descrição da Issue
Será uma reunião para os tecnólogos passarem toda a visão ao passar o backlog para o código.

## Tasks:
- [x] Reunião com os tecnólogos 

## Critérios de Aceitação:
- [x] O backlog ter sido discutido em conjunto.

**Comment by Thais-ra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Time-Capivara-6102b4a201b9d1001095882d/issues/fga-eps-mds/2021-1-Bot/230?planning-poker) with ZenHub @kayrocesar @Ericklevy @DouglasMonteles @LamequeFernandes

**Comment by Thais-ra** [comment]
Ontem nos reunimos para discutir e tirar dúvidas de alguns pontos do backlog, além de adicionar algumas US que julgamos agregar valor ao produto final.
Foi acordado a adição de tópicos específicos sobre o uso de máscaras e informações sobre as mesmas.
Além de um maior refinamento de pesquisa a respeito dos dados que o bot irá devolver ao usuário, com a opção de filtrar por período.
