### ISSUE TITLE
Renumerar  US que já foram feitas de acordo com a nova versão do Backlog

### ISSUE THREAD

**Issue by kayrocesar** [fga-eps-mds/2021-1-Bot#244]
## Descrição da Issue

Renumerar as US já feitas de forma a estarem compatíveis com a nova versão do Backlog.

## Tasks:
- [x] Renumerar  US

**Comment by LamequeFernandes** [comment]
*Lista de US compatíveis com a nova versão do Backlog:*

FT01: Cumprimento/Despedida
US01 - OK
US02 - OK
US03 - OK
US04 - OK
US05 - OK

FT02: Apresentação de funcionalidades
US06 - OK

FT03: Transmissão e prevenção
US07 - OK
US08 - OK
US09 - OK
US10 - OK
US11 - Fazendo(Kayro)
US12 - Fazendo(Kayro)
US13 - OK
US14 - Fazendo(Douglas)
US15 - Fazendo(Douglas)
US16 - Fazendo(Douglas)
US17 - Fazendo(Douglas)

FT04: Regras para lugares específicos
US18 - OK
US19 - OK
US20 - OK
US21 - OK
US22 - OK
US23 - OK 
US24 - OK
US25 - Fazendo (Kayro) 

FT05: Como continuar trabalhando de maneira segura
US26 - Fazendo(Equipe Capivaras)
US27 - Fazendo(Equipe Capivaras)

FT06: Preciso pegar transporte público
US28 - Fazendo(Equipe Capivaras)

FT07: Home office e saúde mental
US29 -
US30 -
US31 -

FT08: Vacinação
US32 -
US33 -
US34 -
US35 -
US36 -
US37 -
US38 -
US39 -
US40 -

FT09: Detecção
US41 - Fazendo(Equipe Capivaras)
US42 -
US43 -
US44 - 

FT10: Lembrete de vacinação
US45 -
US46 -

FT11: Avisos e cuidados
US47 -
US48 -
US49 -
US50 -
US51 -
US52 -
