### ISSUE TITLE
Estabelecer reuniões ordinárias com representantes de todos os grupos presentes (entre os PO)

### ISSUE THREAD

**Issue by gatotabaco** [fga-eps-mds/2021-1-Bot#25]

**Comment by gatotabaco** [comment]
Mudei o título pois em reunião concluímos que seria mais proveitoso que fossem os PO a se reunirem com essa periodicidade.

**Comment by AnaCarolinaRodriguesLeite** [comment]
Estabelecemos que as reuniões seriam feitas a cada interação, dúvida, modificação, conclusão, verificação do andamento, atualização dos respectivos grupos. Acontecendo por meio de comunicação por mensagem pelo telegram ou quando mais necessário estabelecendo comunicação por video chamada, meet.
