### ISSUE TITLE
Bug na API do telegram

### ISSUE THREAD

**Issue by Thais-ra** [fga-eps-mds/2021-1-Bot#252]
## Descrição da Issue

O bot não roda por conta de problemas na api do telegram:

https://github.com/fga-eps-mds/2021-1-Bot/commit/c1e559004972cb5071a5322485d147ac98ff57a7
![image](https://user-images.githubusercontent.com/35047444/134998554-48d770c9-e5fa-4fa2-b013-356d5adc9141.png)

A solução momentanea é comentar as seguintes linhas no arquivo bot/credentials.yml:

![image](https://user-images.githubusercontent.com/35047444/134998876-05e2fadc-8bed-468c-98ae-7a453b25029f.png)

## Critérios de Aceitação:
- [ ] Fazer a API voltar a funcionar

**Comment by Ericklevy** [comment]
Se possível todos os integrantes do bot coloquem isso no env
BOT_ACCESS_TOKEN=1980888238:AAHhqtDRTmd1r8YAIGJSWhIy_h_ywseRGqI
BOT_USER_NAME=alliga_bot
BOT_URL=https://alligabot.herokuapp.com/

**Comment by Ericklevy** [comment]
usa a variavel de ambiente
