### ISSUE TITLE
Implementação da US27

### ISSUE THREAD

**Issue by Thais-ra** [fga-eps-mds/2021-1-Bot#254]
## Descrição da Issue
Implementar a US27 - |Eu, como funcionário, desejo saber os cuidados que devo ter no atendimento aos clientes.

## Critérios de Aceitação:
- [x] US27
- [x] A issue deverá em conta a versão 2 do backlog

**Comment by LamequeFernandes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Time-Capivara-6102b4a201b9d1001095882d/issues/fga-eps-mds/2021-1-Bot/254?planning-poker) with ZenHub @AnaCarolinaRodriguesLeite @gatotabaco @klmurussi @Thais-ra

**Comment by gatotabaco** [comment]
Possível referência https://coronavirus.saude.mg.gov.br/blog/152-coronavirus-no-trabalho

**Comment by LamequeFernandes** [comment]
US27 implementada na branch feature#254/US27.

**Comment by LamequeFernandes** [comment]
Referencias para a realização da US27:
https://blog.cielo.com.br/dicas-e-historias-de-sucesso/dicas-para-atender-clientes-em-tempos-de-covid-19/
http://www.capital.sp.gov.br/noticia/coronavirus-como-garantir-a-seguranca-no-atendimento-ao-publico-em-tempos-de-pandemia
