### ISSUE TITLE
Implementação da US29

### ISSUE THREAD

**Issue by AmandaNbr** [fga-eps-mds/2021-1-Bot#257]
## Descrição da Issue
Pareamento para realizar a implementação da US29: "Eu, como usuário, desejo saber se as vacinas são seguras".

## Critérios de Aceitação:
- [x] Bot respondendo corretamente
- [x] Estar presente no backlog

**Comment by PedroLSF** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plus-Ultra-6102be6967f8c60014c04fdd/issues/fga-eps-mds/2021-1-Bot/257?planning-poker) with ZenHub @AmandaNbr

**Comment by PedroLSF** [comment]
#Descrição
Fizemos uma reunião para "Pair Programming", iniciamos e avançamos na US257
