### ISSUE TITLE
Discutir a viabilidade de implementação das US45 e US46

### ISSUE THREAD

**Issue by kayrocesar** [fga-eps-mds/2021-1-Bot#303]
## Descrição da Issue
Discutir a viabilidade de implementação das seguintes US:

US45 | Eu, como usuário, desejo cadastrar a data da próxima dose da vacina | Must | 8
-- | -- | -- | --
US46 | Eu, como usuário, desejo ser lembrado da próxima dose da vacina | Must | 8

## Tasks:
- [ ]  Avaliar a implementação da US45
- [ ]  Avaliar a implementação da US46

**Comment by DouglasMonteles** [comment]
**Organizando as ideias, a gente teria as seguintes etapas:**

**Na US45:**
- Criação da intent, story e do formulário;
- Bot vai pegar a data informada e salvar em um slot (espécie de variável)
- Criamos uma action em uma classe Python para pegar essa data e salvar em algum lugar (Banco de dados, .TXT, .CSV, etc)
- Dados a serem salvos: id_usuario e data_vacina, por exemplo

**Na US46:**
- Esta US é um pouco diferente, já que ela não é acionada pelo usuário, mas ela é responsável por avisar o usuário que chegou o dia de tomar a segunda dose;
- Basicamente, esta US deve ser executar um procedimento que verifica todo dia se a data de hoje é igual a alguma data cadastrada, se sim, o usuário que cadastrou aquela data deve ser notificado com alguma mensagem;
- Esse procedimento deve ser executado a partir execução do servidor de actions;
