### ISSUE TITLE
Criar protótipo de baixa fidelidade

### ISSUE THREAD

**Issue by Thais-ra** [fga-eps-mds/2021-1-Bot#31]
## Descrição da Issue
Criar protótipo de baixa fidelidade em papel para melhor entender o contexto do produto e das necessidades do usuário.

## Critérios de Aceitação:
- [ ] Protótipo deve refletir todos os requisitos funcionais
- [ ] Todos os membros do time de desenvolvimento devem participar do desenvolvimento do protótipo.
- [ ] O protótipo deve ser em papel
- [ ] Cada membro deve comentar na issue com seus respectivos protótipos

**Comment by Thais-ra** [comment]
![photo_2021-08-11_17-26-39](https://user-images.githubusercontent.com/35047444/129098619-b2a0515f-2a70-4e93-bed7-7ca080183d4d.jpg)
![photo_2021-08-11_17-26-43](https://user-images.githubusercontent.com/35047444/129098626-5945f328-00d8-4e7d-8d04-c7d3e063b922.jpg)

**Comment by gatotabaco** [comment]
![p1](https://user-images.githubusercontent.com/54778783/129114238-43d92282-ba70-4bdb-9e9b-876dd8a42cfb.jpeg)

**Comment by AnaCarolinaRodriguesLeite** [comment]
![Protótipo de baixa fidelidade_page-0001](https://user-images.githubusercontent.com/49570180/129123530-aa8c1625-fcec-49d9-a0dc-eb76da2430fe.jpg)

**Comment by LamequeFernandes** [comment]
![photo_2021-08-11_22-32-46](https://user-images.githubusercontent.com/79016306/129124600-08f11c38-c975-44ae-8543-eda8aa3b3d09.jpg)
![photo_2021-08-11_22-32-54](https://user-images.githubusercontent.com/79016306/129124603-df63969d-891a-49b5-b36d-dbe8d139e1f6.jpg)
![photo_2021-08-11_22-32-57](https://user-images.githubusercontent.com/79016306/129124614-1e84ba5f-7d4e-484e-94ea-e116c156a2d2.jpg)

**Comment by klmurussi** [comment]
![WhatsApp Image 2021-08-18 at 22 25 58](https://user-images.githubusercontent.com/52364259/129993082-84b41387-66a2-4740-9669-53c7ed136a58.jpeg)
![WhatsApp Image 2021-08-18 at 22 25 58 (1)](https://user-images.githubusercontent.com/52364259/129993085-086b2c1a-a369-465d-91e6-183f2fe3920d.jpeg)
![WhatsApp Image 2021-08-18 at 22 25 58 (2)](https://user-images.githubusercontent.com/52364259/129993092-0bc57380-fdba-4712-82ef-9266894f38ac.jpeg)

**Comment by MegahNevel** [comment]
![F2360041-57E4-4B2C-B6C6-C6B04C3BB43E](https://user-images.githubusercontent.com/36899389/130674705-37676e2e-cb5d-4d8a-b4bd-4cc022434aea.jpeg)
Uma seta é mensagem enviada pelo usuário, duas setas são respostas do Bot.
Eu foquei mais no diálogo do que na criação de telas pois não temos certeza em que aplicativo o bot vai operar, e isso afeta mudanças no layout e em usabilidade.
