### ISSUE TITLE
Adição de US no backlog

### ISSUE THREAD

**Issue by Thais-ra** [fga-eps-mds/2021-1-Bot#335]
## Descrição da Issue
Durante a criação da US43 (Eu, como usuário com suspeita de covid, desejo saber qual tipo de exame devo fazer e porque), sentimos a necessidade de separar essa issue em duas.
Uma para explicar ao usuário sobre quais são os tipos de testes, um pouco sobre como eles funcionam, e outra para auxiliar o usuário qual seria o exame mais indicado para o caso dele.

**Comment by Thais-ra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Time-Capivara-6102b4a201b9d1001095882d/issues/fga-eps-mds/2021-1-Bot/335?planning-poker) with ZenHub @LamequeFernandes @klmurussi @gatotabaco @AnaCarolinaRodriguesLeite

**Comment by gatotabaco** [comment]
@Thais-ra isso tá sem estimate
