### ISSUE TITLE
Alteração no documento de backlog

### ISSUE THREAD

**Issue by Thais-ra** [fga-eps-mds/2021-1-Bot#365]
## Descrição da Issue
Adicionar no backlog uma tabela indicando quais US foram feitas e as não feitas, excluir a US06 e alterar a US02.

Tasks:
- [ ] Adição de uma tabela no backlog
- [x] Excluir a US06
- [x] Alterar a US02

Obs: seguir a tabela de [Us's feitas](https://docs.google.com/spreadsheets/d/11hdK5GiReOhe8lYYIOEQbCiYZXK2g69iQaX6faR0_vw/edit#gid=0)

**Comment by Thais-ra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Time-Capivara-6102b4a201b9d1001095882d/issues/fga-eps-mds/2021.1-AlligaBot/365?planning-poker) with ZenHub @AnaCarolinaRodriguesLeite @gatotabaco @klmurussi @LamequeFernandes

**Comment by kayrocesar** [comment]
As US 14 e 16 foram mescladas.

|ID|User Story|Prioridade|Pontos|
|----------|-----------|---------|---------|
|US14|Eu, como usuário, desejo saber qual a quantidade de infectados por covid na minha cidade/estado/país|Should| 8 |
|US16|Eu, como usuário, desejo saber qual a quantidade de mortos por covid na minha cidade/estado/país|Should| 8 |
|US  mesclada|Eu, como usuário, desejo saber qual a quantidade de infectados por covid na minha cidade e quantidade de mortos por covid na minha cidade|Should| 8 |

**Comment by kayrocesar** [comment]
@Thais-ra  Outra mudança importante : A US47 não existe ,pois o ato de ser lembrado ja é feito pela US46 quando ele cadastra a próxima dose.

ID | User Story | Prioridade | Pontos
-- | -- | -- | --
US46 | Eu, como usuário, desejo cadastrar a data da próxima dose da vacina | Must | 8
<strike>US47 <strike>| <strike>Eu, como usuário, desejo ser lembrado da próxima dose da vacina<strike> | <strike>Must<strike> | <strike>8<strike>
