### ISSUE TITLE
Realizar testes rasa da US33 até a US38 

### ISSUE THREAD

**Issue by Thais-ra** [fga-eps-mds/2021-1-Bot#366]
## Descrição da Issue
Implementação de testes nas US33 a US38 

## Tasks:
- [ ] US33
- [ ] Us34
- [x] US35
- [x] US36
- [x] US37
- [x] US38

**Comment by Thais-ra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Time-Capivara-6102b4a201b9d1001095882d/issues/fga-eps-mds/2021.1-AlligaBot/366?planning-poker) with ZenHub @AnaCarolinaRodriguesLeite @gatotabaco @klmurussi @LamequeFernandes

**Comment by Thais-ra** [comment]
A US34 não vai ser feita

**Comment by klmurussi** [comment]
Mulher, e vc vai votar tbm não? kkkk
