### ISSUE TITLE
Bugs no domain

### ISSUE THREAD

**Issue by LamequeFernandes** [fga-eps-mds/2021-1-Bot#387]
## Descrição da Issue
Resolvendo bugs que apareceram no domain.

## Tasks:
- [x] Bugs resolvidos.

## Critérios de Aceitação:
- [x] bot rodando corretamente.

**Comment by LamequeFernandes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Time-Capivara-6102b4a201b9d1001095882d/issues/fga-eps-mds/2021.1-AlligaBot/387?planning-poker) with ZenHub @AnaCarolinaRodriguesLeite @gatotabaco @klmurussi @Thais-ra

**Comment by gatotabaco** [comment]
@LamequeFernandes essa Issue está mal escrita. Não consigo saber do que se trata ao ler e a votação fica difícil! Se possível dá uma atualizada para sabermos do que se trata o bug e em que ele está afetando.

abraço <3

**Comment by LamequeFernandes** [comment]
@gatotabaco resolvi bugs que estava ocorrendo por conta de espaçamentos incorretos.
E padronizei algumas coisas no código como quebras de linha e espamentos apagos o -text, por exemplo.

**Comment by LamequeFernandes** [comment]
TODOS os commits relizados para essa issue foram direcionadas para a issue de numero #384. Por falta de atenção acabei cometendo esse erro.

**Comment by LamequeFernandes** [comment]
bugs resolvidos e codigo mais padronizado.

**Comment by gatotabaco** [comment]
@LamequeFernandes essa issue está sem estimate

**Comment by LamequeFernandes** [comment]
bugs corrigidos
