### ISSUE TITLE
Avanço nas noções de tecnologistas e usos do Rasa

### ISSUE THREAD

**Issue by Ericklevy** [fga-eps-mds/2021-1-Bot#45]
## Descrição da Issue
Estudar de formar assinta docker e o uso do framework Rasa

## Tasks:
- [x] Configurar o ambiente na máquina segundo o docker.
- [x] Estudar a framework rasa e fazer protótipos de bot.

**Comment by Ericklevy** [comment]
Estudamos o básico do bot por enquanto  ,configuramos o docker com wsl e testamos o bot inicial

**Comment by DouglasMonteles** [comment]
Durante o estudo, utilizamos o Windows 10 com WSL 2 rodando o Docker no Ubuntu. Baixamos a imagem docker do rasa na versão 2.8.2 e fizemos o tutorial presente na documentação do rasa sobre a criação de uma assistente virtual cuja comunicação foi feita apenas pelo terminal.

Link: https://rasa.com/docs/rasa/docker/building-in-docker/

**Comment by Ericklevy** [comment]
Imagem do teste usado.
![image](https://user-images.githubusercontent.com/48847770/129487907-b0ce7667-e8f5-4cbe-bc91-d2dc21ef40fa.png)
