### ISSUE TITLE
Escolha da plataforma

### ISSUE THREAD

**Issue by victorear05** [fga-eps-mds/2021-1-Bot#46]
## Descrição da Issue
Issue com o Objetivo de definir a plataforma a ser utilizada.

## Tasks:
Pesquisar sobre as plataformas:
- [x] WhatsApp
- [x] Telegram
- [x] Facebook
 
## Critérios de Aceitação:
- [ ] Avaliar a melhor plataforma para implementação

**Comment by victorear05** [comment]
A integração do rasa com o telegram é facilmente feita usando o BotPai do telegram e obtendo as credenciais, e após colocando-a no bot rasa já criado, via prompt de comando mesmo, no link abaixo tem a devida explicação:
https://rasa.com/docs/rasa/connectors/telegram
A plataforma telegram deve ter um acesso menor, quando comparado com outras plataformas, como por exemplo o WhatsApp, ou Facebook Messenger, porém é disponibilizada pelo próprio telegram de forma gratuita e fácil.

**Comment by matheusrazor** [comment]
A integração do rasa com o whatsapp é feita de forma mais fácil a partir de empresas terceirizadas oficiais, como Twilio. Porém, tais aplicações são pagas.

**Comment by matheusrazor** [comment]
A integração do rasa com o whatsapp é feita de forma mais fácil a partir de empresas terceirizadas oficiais, como o Twilio. Porém, essas soluções são pagas e o período de testes é curto.
Outra opção é usando uma API não-oficial como https://github.com/mukulhase/WebWhatsapp-Wrapper. Porém a integração com o rasa não é clara e o bot pode ser banido pelo whatsapp.

**Comment by klmurussi** [comment]
A integração do rasa com o facebook messenger é feita de forma gratuita a partir do próprio facebook. Deve adicionar credenciais do Facebook a um arquivo de credenciais que o Rasa usará durante a integração. 
Nos links abaixo explica melhor https://rasa.com/docs/rasa/connectors/facebook-messenger/
https://ichi.pro/pt/conectando-o-chatbot-rasa-ai-ao-facebook-messenger-119856672550333

Obs.: o facebook messenger agora tem integração com o instagram, mas não sei se o bot funcionaria pros dois sites

**Comment by klmurussi** [comment]
Telegram e Facebook venceram
