### ISSUE TITLE
Definições de papeis

### ISSUE THREAD

**Issue by PedroLSF** [fga-eps-mds/2021-1-Bot#5]
- [x] Scrum master: @AmandaNbr 
- [x] PO: @PedroLSF 
- [x] Arquiteto: @victorear05 
- [x] DevOPS: @yudi-azvd 
- [x] #9 @Ericklevy 
- [x] Tecnologista @DouglasMonteles

**Comment by LuizPettengill** [comment]
A intenção dessa issue é para cada membro de cada grupo marcar seu papel?

**Comment by yudi-azvd** [comment]
não kkk é só do nosso grupo. mas seria interessante colocar o link das issues de definição de papeis dos outros grupos também
