### ISSUE TITLE
Personalidade e Identidade Visual do Bot

### ISSUE THREAD

**Issue by klmurussi** [fga-eps-mds/2021-1-Bot#55]
## Descrição da Issue
Dar "vida" ao bot

## Tasks:
- [x] Nome
- [x] Logo
- [x] MBTI
- [x] Paleta de Cores
- [x] Outros

## Critérios de Aceitação:
- [x] Todos os integrantes dos três grupos devem aprovar

**Comment by klmurussi** [comment]
Idéias a serem avaliadas: 

Nome: ~Cuca~ Ideia inicial, mas é uma figura do folclore brasileiro e importante para algumas culturas
Logo: Jacaré

26 anos, agente da saúde
atensioso
legal (como o vitinho do sus)
otaku

cor principal: azul (transparece tranquilidade)

**Comment by AmandaNbr** [comment]
Nome: -
Logo: -
Mbti: INFP
Cores: Verde e azul (tons pasteis talvez)

Eu imagino o bot exatamente assim, só que menino:
![image](https://user-images.githubusercontent.com/44625056/130685710-a0e9c5d2-ff11-47ac-bea4-6f4d1c3874f7.png)

**Comment by klmurussi** [comment]
as cores verdes e azuis foram escolhidas para a paleta de cores, assim como o novo nome do bot (AlligaBot)

**Comment by klmurussi** [comment]
como o padrão de fonte, botões etc será do telegram ou outro ambiente, falta atualizar com os dados do github pages no doc de identidade visual

**Comment by MegahNevel** [comment]
Algumas imagens por [Abraham Portilla](https://www.artstation.com/abrahamportilla_21)
![image](https://user-images.githubusercontent.com/36899389/132020114-e6e3e789-d1d4-4b2e-a48a-1546c83b6220.png)
![image](https://user-images.githubusercontent.com/36899389/132020177-fe396b8d-1e2f-41a5-924a-6d030631b0b7.png)
![image](https://user-images.githubusercontent.com/36899389/132020292-11bc65e9-6b67-4798-b027-63ed157bb811.png)
![image](https://user-images.githubusercontent.com/36899389/132020233-bf4664f3-fc05-4022-9547-c161b9660f5a.png)
![image](https://user-images.githubusercontent.com/36899389/132020053-4110ebfa-a4e5-41ab-b7c4-3f4371ac2397.png)

**Comment by klmurussi** [comment]
Falta a introdução do doc de identidade visual
