### ISSUE TITLE
Protótipo de baixa fidelidade

### ISSUE THREAD

**Issue by HenriqueHida** [fga-eps-mds/2021-1-Bot#61]
## Descrição da Issue
Desenhar um protótipo de baixa fidelidade do projeto.

## Critérios de Aceitação:
- [ ] Desenho feito em papel.
- [ ] Todos os membros do grupo devem anexar nos comentários desta Issue seus protótipos.

**Comment by matheusrazor** [comment]
![prototipoMDS](https://user-images.githubusercontent.com/53947083/131268116-67b151ff-81e8-4a39-a847-5b9fd61a3142.png)
