### ISSUE TITLE
Sprint 0 - Tarefa de pesquisa - possíveis linguagens e framework que poderem ser usadas para criação do chat bot

### ISSUE THREAD

**Issue by Ericklevy** [fga-eps-mds/2021-1-Bot#8]
- [x] Pesquisa sobre linguagem
- [x] Pesquisa sobre frameworks

**Comment by Ericklevy** [comment]
Links da pesquisa para uso.
[](https://hackel.com.br/chatbot/)

**Comment by yudi-azvd** [comment]
Coloca "Sprint 0 - Tarefa de pesquisa" no título só pra ficar mais fácil de achar/pesquisar
