### ISSUE TITLE
Criação do documento de visão

### ISSUE THREAD

**Issue by Thais-ra** [fga-eps-mds/2021-1-Bot#87]
## Descrição da Issue
Iniciar o documento de visão.

Segue um exemplo de como deve ficar
https://fga-eps-mds.github.io/2018.2-Kalkuli/docs/docVisao

## Critérios de Aceitação:
- [x] O documento deverá seguir o template da IBM
https://www.ibm.com/support/knowledgecenter/pt-br/SSYMRC_6.0.5/com.ibm.rational.rrm.help.doc/topics/r_vision_doc.html

**Comment by gatotabaco** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Time-Capivara-6102b4a201b9d1001095882d/issues/fga-eps-mds/2021-1-Bot/87?planning-poker) with ZenHub @Thais-ra @AnaCarolinaRodriguesLeite @LamequeFernandes
