### ISSUE TITLE
Elicitação de requisitos

### ISSUE THREAD

**Issue by AnaCarolinaRodriguesLeite** [fga-eps-mds/2021-1-Bot#89]
## Descrição da Issue
Para construção do backlog é necessário antes ter requisitos que estipulem as funcionalidades macros do projeto, exaurindo de forma ampla as possibilidades mais esperadas pelo usuário.

## Tasks:
- [x] Documentação dos requisitos seguindo o template.

## Critérios de Aceitação:
- [ ] Revisão por um membro de uma das 3 equipes.
- [ ] Notificar atualização.

**Comment by gatotabaco** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Time-Capivara-6102b4a201b9d1001095882d/issues/fga-eps-mds/2021-1-Bot/89?planning-poker) with ZenHub @Thais-ra @AnaCarolinaRodriguesLeite @LamequeFernandes @klmurussi
